services:
  chroma:
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"

  ingest:
    build:
      context: ./packages/ingest
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - chroma

volumes:
  chroma_data: